# Generated by Django 5.0.2 on 2024-02-26 12:19

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='news.author'),
        ),
    ]
